Collections_app/config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :collections
  resources :companies
  resources :ratings, only: :update
  devise_for :users
  root 'home#index'

  # Talvez colocar aquele esquema de rota especial de login (de logout não precisa), isso no application_controller
  # Para isso foi criado o home/show.html.erb

  get 'collectors/index'
  get 'collectors/show'
  get 'collectors/add_item'
  get 'collectors/remove_item'
  get 'collectors/unfollow_collection'
  get 'companies/index'
  get 'companies/show'
  get "user", to: "login#user"

end

Collections_app/app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /controllers
  # GET /controllers.json
  def index
    if user_signed_in?
      if current_user.company?
        @collections = current_user.company.collections
      else
        @collections = []
        current_user.collector.items.each do |item|
         @collections << item.collection
        end
        @collections.uniq!
      end
    end
  end
end

Collections_app/app/views/home/_homepage.html.erb
<div class="homepage">
  <h1> Welcome, <%= current_user.username %> </h1>
  <div class="field">
  	<% if current_user.avatar? %>
  		<%= image_tag current_user.avatar.url(:thumb) %>
  	<% end %>
  </div>
  <!-- <h2> * Menu *</h2> -->
  &nbsp;	

  <div class="btn-group btn-group-lg" role="group" aria-label="Menu">
    <%= link_to 'Collections', collections_path, class: "btn btn-default", type: "button" %>
    <%= link_to 'Companies', companies_path, class: "btn btn-default", type: "button" %>
    <%= link_to 'Collectors', collectors_index_path, class: "btn btn-default", type: "button" %>
  </div>
  &nbsp;	

  <!--Area do usuário-->
  <h2>Your collections</h2>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Begin date</th>
        <th>Description</th>
        <th>Number of collectors</th>
        <th colspan="3" width="170"></th>
      </tr>
    </thead>

    <tbody>
      <% @collections.each do |collection| %>
        <tr class="table-data">
          <td align="center" valign="center"><%= collection.name %></td>
          <td align="center" valign="center"><%= collection.begin_date %></td>
          <% if collection.description.length > 15 %>
            <td align="center" valign="center"><%= collection.description[0, 20].chomp(" ").concat("...") %></td>
          <% else %>
            <td align="center" valign="center"><%= collection.description %></td>
          <% end %>
          <td align="center" valign="center"><%= collection.collectors_count %></td>
          <!-- maybe coll_count is collectors_count now -->
          <td><%= link_to 'Show', collection %></td>
          <% if current_user.company? %>
            <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
            <td><%= link_to 'Delete', collection, method: :delete, data: { confirm: 'Are you sure you want to delete "' + collection.name + '"?' } %></td>
          <% else %>
          	<td><%= link_to 'Unfollow', collectors_unfollow_collection_path(collection: collection) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if current_user.level == "company" %>
    <%= link_to 'New Collection', new_collection_path %></br></br>
  <% end %>
  <%= link_to 'Edit account', edit_user_registration_path %></br>
</div>

Collections_app/app/views/home/index.html.erb
<% if user_signed_in? %>
	<%= render 'homepage'%>
<% else %>

	<div class="intro-text">
		<h2> Welcome to GemCase! </h2>
		<br>

		<p> Gemcase is a website designed as a catalog for your collections, </p>
		<p> with the added social features that are very much prominent in today's industry. </p>
		<p> You can keep track of your colletions, as well as see your's friend's, </p>
		<p> and rate them based on your opinions. </p>

		<br>
		<h3> Proceed to our login page to begin your GemCase experience! </h3>
		<%= link_to 'Login', new_user_session_path, class: "btn btn-primary btn-lg", role: "button" %>
	</div>
<% end %>

Collections_app/app/views/home/show.html.erb
<p> Oi </p>