Collections_app/config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :collections
  resources :companies
  resources :ratings, only: :update
  devise_for :users
  root 'home#index'

  # Talvez colocar aquele esquema de rota especial de login (de logout não precisa), isso no application_controller
  # Para isso foi criado o home/show.html.erb

  get 'collectors/index'
  get 'collectors/show'
  get 'collectors/add_item'
  get 'collectors/remove_item'
  get 'collectors/unfollow_collection'
  get 'companies/index'
  get 'companies/show'
  get "user", to: "login#user"

end

Collections_app/app/models/collector.rb
class Collector < ApplicationRecord
  belongs_to :user
  has_many :collector_items
  has_many :items, :through => :collector_items
  has_many :ratings
end

Collections_app/app/controllers/collectors_controller.rb
class CollectorsController < ApplicationController
  def index
    @collectors = ::Collector.all
  end


  def show
    @collections = []
    @collector = ::Collector.find_by_id(params[:collector])
    @collector.items.each do |item|
      @collections.append(item.collection)
    end
    @collections.uniq!
  end

  def add_item
    item =  Item.find_by_id(params[:item])
    current_user.collector.collector_items.create(item: item)
    redirect_to collection_path(item.collection)
  end

  def remove_item
    item =  Item.find_by_id(params[:item])
    c = CollectorItem.find_by(item: item)
    c.destroy!
    redirect_to collection_path(item.collection)
  end

  def unfollow_collection
    current_user.collector.items.each do |item|
      if item.collection.id == params[:collection].to_i
        CollectorItem.find_by(item: item, collector: current_user.collector).destroy!
      end
    end
    redirect_to root_path
  end
end

Collections_app/app/helpers/collectors_helper.rb
module CollectorsHelper
end

Collections_app/app/views/collectors/index.html.erb
<div class="user-index">
  <h1>Collectors</h1>

  <table cellpadding="10" cellspacing="10">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @collectors.each do |collector| %>
        <tr>
          <td align="center" valign="center"><%= collector.name %></td>
          <td><%= link_to 'Show', collectors_show_path(collector: collector) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

Collections_app/app/views/collectors/show.html.erb
<div class="general-show">  
  <p>
    <strong>Name:</strong>
    <%= @collector.name %>
  </p>

  <p>
    <strong>Photo:</strong>
    <div class="field">
    	<% if @collector.user.avatar? %>
    		<p><%= image_tag @collector.user.avatar.url(:thumb) %></p>
    	<% end %>
    </div>

  <p><strong>List of collections:</strong></p>
  <table cellpadding="10" cellspacing="10" style="margin-left: 500px">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @collections.each do |collection| %>
        <tr>
          <td align="center" valign="center"><%= collection.name %></td>
          <td><%= link_to 'Show', collection %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </p>

  <br>
  <%= link_to 'All Collectors', collectors_index_path %> <br>
</div>