Collections_app/config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :collections
  resources :companies
  resources :ratings, only: :update
  devise_for :users
  root 'home#index'

  # Talvez colocar aquele esquema de rota especial de login (de logout não precisa), isso no application_controller
  # Para isso foi criado o home/show.html.erb

  get 'collectors/index'
  get 'collectors/show'
  get 'collectors/add_item'
  get 'collectors/remove_item'
  get 'collectors/unfollow_collection'
  get 'companies/index'
  get 'companies/show'
  get "user", to: "login#user"

end

Collections_app/app/models/collection.rb
class Collection < ApplicationRecord
  has_many :items
  belongs_to :company
  validates :name, :description, presence: true


  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  # Validate filename
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]
  # Explicitly do not validate
  do_not_validate_attachment_file_type :avatar
  
  def average_rating
    sum = 0
    zeros = 0;
    if items.count == 0
      return 0
    end
    items.each do |item|
      if item.average_rating == 0
        zeros += 1
      end
      sum += item.average_rating
    end
    if items.count == zeros
      return 0
    end
    return  sum / (items.count - zeros)
  end
  
  def collectors_count
    item_ids = self.items.pluck :id # Recebe os IDs dos itens da coleção em um array
    collector_ids = CollectorItem.where("item_id in (?)", item_ids).pluck(:collector_id).uniq # Recebe os IDs dos colecionadores dos itens da coleção sem repetição
    # Collector.where("id in (?)", collector_ids)
    return collector_ids.size
  end
end

Collections_app/app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
    if !user_signed_in?
      redirect_to controller: "collections", action: "index"
    end
  end

  # POST /collections
  # POST /collections.json
  def create
    if user_signed_in?
      @collection = Collection.new(collection_params)
      @collection.company = current_user.company
      respond_to do |format|
        if @collection.save
          format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
          format.json { render :show, status: :created, location: @collection }
        else
          format.html { render :new }
          format.json { render json: @collection.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to controller: "collections", action: "index"
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    if user_signed_in?
      respond_to do |format|
        if @collection.update(collection_params)
          format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
          format.json { render :show, status: :ok, location: @collection }
        else
          format.html { render :edit }
          format.json { render json: @collection.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to controller: "collections", action: "index"
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    if user_signed_in?
      @collection.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Collection "' + @collection.name + '" was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to controller: "collections", action: "index"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :begin_date, :description, :coll_count, :avatar, :avatar_cache)
    end
end

Collections_app/app/helpers/collections_helper.rb
module CollectionsHelper
end

Collections_app/app/views/collections/_form.html.erb
<%= form_for(collection, html: { multipart: true }) do |f| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :begin_date %>
    <%= f.date_select :begin_date %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Collections_app/app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Home page', root_path %>

Collections_app/app/views/collections/index.html.erb
<div class="homepage">
  <p id="notice"><%= notice %></p>

  <h1>Collections</h1>

  <table cellpadding="10" cellspacing="10">
    <thead>
      <tr>
        <th>Name</th>
        <th>Begin date</th>
        <th>Description</th>
        <th>Number of collectors</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @collections.each do |collection| %>
        <tr>
          <td align="center" valign="center"><%= collection.name %></td>
          <td align="center" valign="center"><%= collection.begin_date %></td>
          <% if collection.description.length > 15 %>
            <td align="center" valign="center"><%= collection.description[0, 20].chomp(" ").concat("...") %></td>
          <% else %>
            <td align="center" valign="center"><%= collection.description %></td>
          <% end %>
          <td align="center" valign="center"><%= collection.collectors_count %></td>
          <td><%= link_to 'Show', collection %></td>
          <% if user_signed_in? && current_user.company? && collection.company == current_user.company %>
            <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
            <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if user_signed_in? && current_user.level == "company" %>
    <%= link_to 'New Collection', new_collection_path %> <br>
  <% end %>

  <br>
</div>

Collections_app/app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'All Collections', collections_path %> <br>
<%= link_to 'Home Page', root_path %>

Collections_app/app/views/collections/show.html.erb
<div class="general-show">  
  <p id="notice"><%= notice %></p>

  <p>
    <% if @collection.avatar? %>
      <p><%= image_tag @collection.avatar.url(:thumb) %></p>
    <% end %>

    <strong>Name:</strong>
    <%= @collection.name %><br>

    <strong>Begin date:</strong>
    <%= @collection.begin_date %><br>

    <strong>Description:</strong>
    <%= @collection.description %><br>

    <strong>Coll count:</strong>
    <%= @collection.collectors_count %><br>

    <p>Collection Rating</p>
    <div id="star"></div>
    <script>
      $('#star').raty({
        readOnly: true,
        score: <%= @collection.average_rating %>,
        path: '/assets'
      });
    </script>
  </p>

  <% if @collection.items.size != 0 %>
    <table cellpadding="10" cellspacing="10">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Collector's count</th>
          <th colspan="3" width="170"></th>
        </tr>
      </thead>
  <% end %>

    <tbody>
      <% @collection.items.each do |item| %>
        <tr>
          <td align="center" valign="center"><%= item.name %></td>
          <td align="center" valign="center"><%= item.description %></td>
          <td align="center" valign="center"><%= item.collectors.size %></td>
          <td><%= link_to 'Show', item %></td>
          <% if user_signed_in? %>
            <% if current_user.company? && item.collection.company == current_user.company %>
              <td><%= link_to 'Edit', edit_item_path(item, :collection => @collection) %></td>
              <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure you want to delete item "' + item.name + '"?' } %></td>
            <% elsif current_user.collector? %>
              <% if current_user.collector.items.include?(item) %>
                <td><%= link_to 'Remove', collectors_remove_item_path(:item => item) %>
              <% else %>
                <td><%= link_to 'Add', collectors_add_item_path(:item => item) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if user_signed_in? %>
    <% if current_user.company? && @collection.company == current_user.company %>
      <%= link_to 'New Item', new_item_path(:collection => @collection) %> |
      <%= link_to 'Edit', edit_collection_path(@collection) %> |
    <% end %>
  <% end %>
  <%= link_to 'Collections', collections_path %> |
  <%= link_to 'Home page', root_path %>

  <br/>
  <br/>
</div>